Import libraries & Create dataset

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age': [25, np.nan, 35, np.nan, np.nan, 40],
    'city': ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', 'Mumbai'],
    'gender': ['Male', 'Female', 'Female', 'Male', 'Female', 'Female'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2   NaN   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4   NaN  Mumbai    Male         120000
4            2   NaN   Delhi  Female          80000
5            5  40.0  Mumbai  Female          95000

Fill Missing Values

In [3]:
# Fill missing age with median
df['age'].fillna(df['age'].median(), inplace=True)

# Fill missing city with mode
df['city'].fillna(df['city'].mode()[0], inplace=True)

df

/tmp/ipykernel_17518/960662115.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)
/tmp/ipykernel_17518/960662115.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['city'].fillna(df['city'].mode()[0], inplace=True)

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0  Mumbai  Female          60000
3            4  35.0  Mumbai    Male         120000
4            2  35.0   Delhi  Female          80000
5            5  40.0  Mumbai  Female          95000

Remove duplicates

In [4]:
df.drop_duplicates(inplace=True)
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0  Mumbai  Female          60000
3            4  35.0  Mumbai    Male         120000
5            5  40.0  Mumbai  Female          95000

Encode categorical columns

In [5]:
from sklearn.preprocessing import LabelEncoder

# Label encode gender
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])

# One-hot encode city
df = pd.get_dummies(df, columns=['city'])

df

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0       1          40000       False         True
1            2  35.0       0          80000        True        False
2            3  35.0       0          60000       False         True
3            4  35.0       1         120000       False         True
5            5  40.0       0          95000       False         True

**Min - Max Scaling**

Min-Max Scaling is used when data has no outliers and we need values in a fixed range (0 to 1). It is useful in distance-based algorithms like KNN and Neural Networks.

In [6]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()

df_minmax = df.copy()
df_minmax[['age', 'annual_income']] = minmax.fit_transform(
    df_minmax[['age', 'annual_income']]
)

df_minmax

   customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1  0.000000       1         0.0000       False         True
1            2  0.666667       0         0.5000        True        False
2            3  0.666667       0         0.2500       False         True
3            4  0.666667       1         1.0000       False         True
5            5  1.000000       0         0.6875       False         True

**Standardisation**

Standardisation is used when data contains outliers or follows normal distribution. It centers the data to mean 0 and variance 1 and is preferred in Logistic Regression, SVM, and PCA.

In [7]:
from sklearn.preprocessing import StandardScaler

standard = StandardScaler()

df_standard = df.copy()
df_standard[['age', 'annual_income']] = standard.fit_transform(
    df_standard[['age', 'annual_income']]
)

df_standard

   customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1 -1.837117       1      -1.410970       False         True
1            2  0.204124       0       0.036179        True        False
2            3  0.204124       0      -0.687396       False         True
3            4  0.204124       1       1.483328       False         True
5            5  1.224745       0       0.578860       False         True